name: Daily24H

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9:00 AM UTC
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  run-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-genai

      - name: Run Python script
        env:
          # This bridges your Repository Secret to the script
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
