import os
from datetime import datetime
from google import genai
from google.genai import types

# 1. Initialize Client
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

def update_index_page(latest_briefing_path, latest_content):
    """Updates index.md to act as the homepage for GitHub Pages."""
    print("🏠 Updating index.md...")
    
    # Header for the dashboard
    header = f"""# 🚀 AI News Intelligence Dashboard
> Last updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} UTC

## 📍 Latest Briefing
{latest_content}

---
## 📚 Archive
"""
    # Generate archive links from existing files in the briefings folder
    archive_links = []
    if os.path.exists("briefings"):
        files = sorted(os.listdir("briefings"), reverse=True)
        for f in files:
            if f.endswith(".md"):
                date_val = f.replace(".md", "")
                archive_links.append(f"* [{date_val}](briefings/{f})")
    
    archive_section = "\n".join(archive_links)
    
    with open("index.md", "w", encoding="utf-8") as f:
        f.write(header + archive_section)

def fetch_and_save_news(topic="Global Tech & AI News"):
    print(f"🔎 Searching for: {topic}...")
    
    # Prompt engineering for better resume-style output
    prompt = f"Summarize the top 5 news stories from the last 24 hours about {topic}. Provide a professional title, a 2-sentence summary for each, and the source link."

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite", 
            contents=prompt,
            config=types.GenerateContentConfig(
                tools=[types.Tool(google_search=types.GoogleSearch())]
            )
        )

        if not response.text:
            print("⚠️ No content generated by AI.")
            return

        # 1. Save dated file
        os.makedirs("briefings", exist_ok=True)
        date_str = datetime.now().strftime("%Y-%m-%d")
        filename = f"briefings/{date_str}.md"

        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"# Daily Briefing: {date_str}\n\n{response.text}")
        
        # 2. Update the Dashboard (index.md)
        update_index_page(filename, response.text)
        
        print(f"✅ Dashboard updated and saved to {filename}")

    except Exception as e:
        print(f"❌ Error: {str(e)}")

if __name__ == "__main__":
    fetch_and_save_news()
