import os
from datetime import datetime
from google import genai
from google.genai import types

# 1. Initialize Client
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

def fetch_and_save_news(topic="Global Tech & AI News"):
    print(f"🔎 Searching for: {topic}...")
    
    prompt = f"Summarize the top 5 news stories from the last 24 hours about {topic}. Include links."

    try:
        # SWITCHED TO FLASH-LITE: This is the most stable free model for search right now
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite", 
            contents=prompt,
            config=types.GenerateContentConfig(
                tools=[types.Tool(google_search=types.GoogleSearch())]
            )
        )

        if not response.text:
            print("⚠️ No content generated by AI.")
            return

        # 2. Save to file
        os.makedirs("briefings", exist_ok=True)
        date_str = datetime.now().strftime("%Y-%m-%d")
        filename = f"briefings/{date_str}.md"

        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"# Daily Briefing: {date_str}\n\n{response.text}")
        
        print(f"✅ News saved to {filename}")

    except Exception as e:
        print(f"❌ Error: {str(e)}")

if __name__ == "__main__":
    fetch_and_save_news()
